### ISSUE TITLE
Client can't connect to MongoDB with Replica Set

### ISSUE THREAD

**Issue by flogoe** [XaverImMuseum/XaverImMuseum#8]
## MongoDB Config

```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1

# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#security:

#operationProfiling:

replication:
    oplogSizeMB: 990
    replSetName: replicaSet

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```

## Error
```
2020-08-14 09:58:49.671  INFO 31589 --- [           main] org.mongodb.driver.cluster               : No server chosen by com.mongodb.internal.async.client.ClientSessionHelper$1@22f80e36 from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=SINGLE, serverDescriptions=[]}. Waiting for 30000 ms before timing out
2020-08-14 09:59:19.679  INFO 31589 --- [999612b34a21a05] org.mongodb.driver.cluster               : No server chosen by WritableServerSelector from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=SINGLE, serverDescriptions=[]}. Waiting for 30000 ms before timing out
2020-08-14 09:59:49.687  INFO 31589 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-14 09:59:49.696 ERROR 31589 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.4.0-M1.jar:2.4.0-M1]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.4.0-M1.jar:2.4.0-M1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.4.0-M1.jar:2.4.0-M1]
        at x.museum.quest.ApplicationKt.main(Application.kt:73) ~[main/:na]
Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=REPLICA_SET, servers=[]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=REPLICA_SET, servers=[]
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:88) ~[spring-data-mongodb-3.1.0-M1.jar:3.1.0-M1]
        at org.springframework.data.mongodb.core.ReactiveMongoTemplate.potentiallyConvertRuntimeException(ReactiveMongoTemplate.java:2808) ~[spring-data-mongodb-3.1.0-M1.jar:3.1.0-M1]
        at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$translateException$91(ReactiveMongoTemplate.java:2791) ~[spring-data-mongodb-3.1.0-M1.jar:3.1.0-M1]
        at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3285) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
        at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
        at com.mongodb.reactivestreams.client.internal.AbstractSubscription.onError(AbstractSubscription.java:139) ~[mongodb-driver-reactivestreams-4.0.4.jar:na]
        at com.mongodb.reactivestreams.client.internal.SingleResultCallbackSubscription.lambda$requestInitialData$0(SingleResultCallbackSubscription.java:41) ~[mongodb-driver-reactivestreams-4.0.4.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.async.client.OperationExecutorImpl$2$1$1.onResult(OperationExecutorImpl.java:138) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.operation.DropCollectionOperation$2.call(DropCollectionOperation.java:111) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.operation.OperationHelper$AsyncCallableWithConnectionCallback.onResult(OperationHelper.java:568) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.operation.OperationHelper$AsyncCallableWithConnectionCallback.onResult(OperationHelper.java:560) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:96) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:92) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:428) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:311) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.connection.BaseCluster.access$800(BaseCluster.java:62) ~[mongodb-driver-core-4.0.4.jar:na]
        at com.mongodb.internal.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:474) ~[mongodb-driver-core-4.0.4.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=REPLICA_SET, servers=[]
        at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:403) ~[mongodb-driver-core-4.0.4.jar:na]
        ... 4 common frames omitted

2020-08-14 09:59:49.698  INFO 31589 --- [           main] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2020-08-14 09:59:49.706  INFO 31589 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete

> Task :bootRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by flogoe** [comment]
Switched to MongoDB Standalone, so this issue is no longer relevant.
